name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual refresh

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Main Stats & Languages
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: salonyranjan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          # PLUGIN: Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_details: percentage
          
          # STYLING
          config_padding: 0, 8%
          config_twemoji: yes
          plugin_pagespeed: no
          
          # OUTPUT
          filename: github-metrics.svg
          optimize: css, xml, svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "chore: update metrics [skip ci]"
          
          # Retry configuration to handle API rate limits
          retries: 3
          retries_delay: 300
